linters:
  enable:
    - nlreturn
    - forcetypeassert
    - errorlint
    - unparam
    - gosec
    - revive
    - goconst
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
